#pragma config(Motor,  port2,           dcMotor1,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           dcMotor2,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           baseServo,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           clawServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool playingNow  = false;
int theTimer;
string stringInt[1];
bool readButton[8] = {false, false, false, false, false, false, false, false};
int lastJoystick = 0;
int lastJoystick2 = 0;
int joyCh2 = 0;
int joyCh3 = 0;
int readPress = 0;
int readJoy = 0;
//PASTE CODE BELOW THIS COMMENT
int mainLength = 71;
string buttonPresses[71] = {"Ch3","Ch3","Ch3","6UD","Ch2","Ch2","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch2","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","Ch3","6UU","Ch2","Ch3","Ch2","Ch3","Ch2","6UD","6UU","Ch2","Ch3","Ch2","Ch3","Ch2"};
int timerValues[71] = {30,110,180,450,2510,2580,2580,2660,3740,3800,3870,4710,4790,4830,7130,7220,7290,7350,7430,7490,8090,8160,11010,11070,11130,11210,11280,13190,13230,13380,13460,13530,14000,14070,14100,14130,14220,16890,17130,17210,17270,21330,21390,21450,22230,22260,22340,23160,23240,23310,23340,23490,23540,23550,23690,23720,23780,23850,25680,25680,25680,25760,25760,25830,26250,27390,27390,27390,27470,27470,27530};
int joystickValues[67] = {26,39,0,25,127,34,127,110,76,0,16,106,127,115,97,73,47,10,0,33,127,112,82,51,22,0,25,37,48,66,72,57,36,20,14,0,10,20,59,127,66,16,0,27,89,125,86,-17,-75,-115,-72,-12,0,27,40,84,127,30,-17,-74,-127,-127,-106,-121,-54,0,0};//PASTE CODE ABOVE THIS COMMENT
//above
task main(){
	clearDebugStream();
	clearTimer(T1);
	motor[baseServo] = 180;
	while(true){
		theTimer = time1[T1];
		if(playingNow == false){
			if(vexRT[Ch2] < 10 && vexRT[Ch2] > -10){
				joyCh2 = 0;
			}
			else{
				joyCh2 = vexRT[Ch2];
			}
			if(vexRT[Ch3] < 10 && vexRT[Ch3] > -10){
				joyCh3 = 0;
			}
			else{
				joyCh3 = vexRT[Ch3];
			}
			motor[dcMotor1] = joyCh3;
			motor[dcMotor2] = joyCh2;
			if(vexRT[Btn7L]){
				motor[baseServo] = -60;
			}
			if(vexRT[Btn7R]){
				motor[baseServo] = 60;
			}
			if(vexRT[Btn7U]){
				//motor[baseServo] = 180;
			}
			if(vexRT[Btn7D]){
				//motor[baseServo] = -180;
			}
			if(vexRT[Btn7L] == false && vexRT[Btn7R] == false){
				motor[baseServo] = 0;
			}
			if(vexRT[Btn8R]){
				motor[clawServo] = -180;
			}
			if(vexRT[Btn8D]){
				motor[clawServo] = 180;
			}
			if(vexRT[Btn6U]){
				motor[armMotor] = -180;
			}
			else if(vexRT[Btn6D]){
				motor[armMotor] = 180;
			}
			else{
				motor[armMotor] = 0;
		}}
		else{
			if(readPress < mainLength){
				if(theTimer >= timerValues[readPress]){
					writeDebugStream(buttonPresses[readPress]);
					if(buttonPresses[readPress] == "7LD"){readButton[0] = true;}
					if(buttonPresses[readPress] == "7LU"){readButton[0] = false;}
					if(buttonPresses[readPress] == "7RD"){readButton[1] = true;}
					if(buttonPresses[readPress] == "7RU"){readButton[1] = false;}
					if(buttonPresses[readPress] == "7UD"){readButton[2] = true;}
					if(buttonPresses[readPress] == "7UU"){readButton[2] = false;}
					if(buttonPresses[readPress] == "7DD"){readButton[3] = true;}
					if(buttonPresses[readPress] == "7DU"){readButton[3] = false;}
					if(buttonPresses[readPress] == "8RD"){readButton[4] = true;}
					if(buttonPresses[readPress] == "8RU"){readButton[4] = false;}
					if(buttonPresses[readPress] == "8DD"){readButton[5] = true;}
					if(buttonPresses[readPress] == "8DU"){readButton[5] = false;}
					if(buttonPresses[readPress] == "6UD"){readButton[6] = true;}
					if(buttonPresses[readPress] == "6UU"){readButton[6] = false;}
					if(buttonPresses[readPress] == "6DD"){readButton[7] = true;}
					if(buttonPresses[readPress] == "6DU"){readButton[7] = false;}
					if(buttonPresses[readPress] == "Ch2"){
						joyCh2 = joystickValues[readJoy];
						readJoy += 1;
					}
					if(buttonPresses[readPress] == "Ch3"){
						joyCh3 = joystickValues[readJoy];
						readJoy += 1;
					}
					readPress += 1;
				}
				if(readButton[0]){
					motor[baseServo] = -60;
				}
				if(readButton[1]){
					motor[baseServo] = 60;
				}
				if(readButton[4]){
					motor[clawServo] = -180;
				}
				if(readButton[5]){
					motor[clawServo] = 180;
				}
				if(readButton[6]){
					motor[armMotor] = -180;
				}
				else if(readButton[7]){
					motor[armMotor] = 180;
				}
				else{
					motor[armMotor] = 0;
				}
				if(readButton[0] == false && readButton[1] == false){
					motor[baseServo] = 0;
				}
				motor[dcMotor1] = joyCh3;
				motor[dcMotor2] = joyCh2;
			}
			else{
				writeDebugStreamLine("\n------------------------");
				writeDebugStreamLine("Autonomous Task Complete");
				playingNow = false;
			}
		}
		if(vexRT[Btn5D] && playingNow == false){
			clearTimer(T1);
			playingNow = true;
			readPress = 0;
			readJoy = 0;
			joyCh2 = 0;
			joyCh3 = 0;
			writeDebugStreamLine("Autonomous Task Attempt");
			writeDebugStreamLine("-----------------------");
		}
		if(vexRT[Btn5U] && playingNow){
			writeDebugStreamLine("\n--- Abort Autonomous Task ---");
			playingNow = false;
		}
		wait1Msec(10);
	}
}
