#pragma config(Motor,  port2,           dcMotor1,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           dcMotor2,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           baseServo,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           clawServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool recordingNow = false;
int theTimer;
string stringInt[1];
bool readButton[8] = {false, false, false, false, false, false, false, false};
int lastJoystick = 0;
int lastJoystick2 = 0;
int joyCh2 = 0;
int joyCh3 = 0;
task main(){
	clearDebugStream();
	clearTimer(T1);
	motor[baseServo] = 0;
	while(true){
		if(vexRT[Ch2] < 10 && vexRT[Ch2] > -10){
			joyCh2 = 0;
		}
		else{
			joyCh2 = vexRT[Ch2];
		}
		if(vexRT[Ch3] < 10 && vexRT[Ch3] > -10){
			joyCh3 = 0;
		}
		else{
			joyCh3 = vexRT[Ch3];
		}
		theTimer = time1[T1];
		motor[dcMotor1] = joyCh3;
		motor[dcMotor2] = joyCh2;
		if(vexRT[Btn7L]){
			motor[baseServo] = -60;
			if(recordingNow){
				if(readButton[0] == false){
					writeDebugStream("['7LD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[0] = true;
				}
			}
		}
		else{
			if(readButton[0]){
				if(recordingNow){
					writeDebugStream("['7LU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[0] = false;
				}
			}
		}
		if(vexRT[Btn7R]){
			motor[baseServo] = 60;
			if(recordingNow){
				if(readButton[1] == false){
					writeDebugStream("['7RD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[1] = true;
				}
			}
		}
		else{
			if(readButton[1]){
				if(recordingNow){
					writeDebugStream("['7RU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[1] = false;
				}
			}
		}
		if(vexRT[Btn7U]){
			//motor[baseServo] = 180;
			if(recordingNow){
				if(readButton[2] == false){
					writeDebugStream("['7UD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[2] = true;
				}
			}
		}
		else{
			if(readButton[2]){
				if(recordingNow){
					writeDebugStream("['7UU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[2] = false;
				}
			}
		}
		if(vexRT[Btn7D]){
			//motor[baseServo] = -180;
			if(recordingNow){
				if(readButton[3] == false){
					writeDebugStream("['7DD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[3] = true;
				}
			}
		}
		else{
			if(readButton[3]){
				if(recordingNow){
					writeDebugStream("['7DU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[3] = false;
				}
			}
		}
		if(vexRT[Btn8R]){
			motor[clawServo] = -180;
			if(recordingNow){
				if(readButton[4] == false){
					writeDebugStream("['8RD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[4] = true;
				}
			}
		}
		else{
			if(readButton[4]){
				if(recordingNow){
					writeDebugStream("['8RU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[4] = false;
				}
			}
		}
		if(vexRT[Btn8D]){
			motor[clawServo] = 180;
			if(recordingNow){
				if(readButton[5] == false){
					writeDebugStream("['8DD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[5] = true;
				}
			}
		}
		else{
			if(readButton[5]){
				if(recordingNow){
					writeDebugStream("['8DU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[5] = false;
				}
			}
		}
		if(vexRT[Btn6U]){
			motor[armMotor] = -180;
			if(recordingNow){
				if(readButton[6] == false){
					writeDebugStream("['6UD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[6] = true;
				}
			}
		}
		else if(vexRT[Btn6D]){
			motor[armMotor] = 180;
			if(recordingNow){
				if(readButton[7] == false){
					writeDebugStream("['6DD', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[7] = true;
				}
			}
		}
		else{
			motor[armMotor] = 0;
		}
		if(vexRT[Btn6U] == false){
			if(readButton[6]){
				if(recordingNow){
					writeDebugStream("['6UU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[6] = false;
				}
			}
		}
		if(vexRT[Btn6D] == false){
			if(readButton[7]){
				if(recordingNow){
					writeDebugStream("['6DU', ");
					sprintf(stringInt, "%d", theTimer);
					writeDebugStream(stringInt);
					writeDebugStream("],");
					readButton[7] = false;
				}
			}
		}
		if(joyCh2 > lastJoystick + 5 || joyCh2 < lastJoystick - 5 || (joyCh2 == 0 && lastJoystick != 0)){
			if(recordingNow){
				writeDebugStream("['Ch2', ");
				sprintf(stringInt, "%d", theTimer);
				writeDebugStream(stringInt);
				writeDebugStream(", ");
				sprintf(stringInt, "%d", joyCh2);
				writeDebugStream(stringInt);
				writeDebugStream("],");
				lastJoystick = joyCh2;
			}
		}
		if(joyCh3 > lastJoystick2 + 5 || joyCh3 < lastJoystick2 - 5 || (joyCh3 == 0 && lastJoystick2 != 0)){
			if(recordingNow){
				writeDebugStream("['Ch3', ");
				sprintf(stringInt, "%d", theTimer);
				writeDebugStream(stringInt);
				writeDebugStream(", ");
				sprintf(stringInt, "%d", joyCh3);
				writeDebugStream(stringInt);
				writeDebugStream("],");
				lastJoystick2 = joyCh3;
			}
		}
		if(vexRT[Btn7R] == false && vexRT[Btn7L] == false){
			motor[baseServo] = 0;
		}
		if(vexRT[Btn5D] && recordingNow == false){
			clearTimer(T1);
			recordingNow = true;
		}
		wait1Msec(10);
	}
}
